# Generated by Django 5.2.16 on 2026-07-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('asset_code', models.CharField(blank=True, max_length=100, verbose_name='资产编码')),
                ('officer_name', models.CharField(max_length=50, verbose_name='民警姓名')),
                ('officer_age', models.IntegerField(default=25, verbose_name='年龄')),
                ('officer_gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=10, verbose_name='性别')),
                ('marker_shape', models.CharField(choices=[('circle', '圆形'), ('triangle', '三角形'), ('square', '方形'), ('diamond', '菱形'), ('pentagon', '五边形'), ('star', '星形'), ('hexagon', '六边形'), ('cross', '十字形')], default='circle', max_length=20, verbose_name='图标形状')),
                ('marker_color', models.CharField(default='#1890FF', max_length=20, verbose_name='图标颜色')),
                ('is_online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('last_report_time', models.DateTimeField(blank=True, null=True, verbose_name='最后上报时间')),
                ('latitude', models.FloatField(default=30.5722, verbose_name='纬度')),
                ('longitude', models.FloatField(default=104.0665, verbose_name='经度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('status', models.CharField(choices=[('recording', '数据录入中'), ('stopped', '停止录入'), ('archived', '已归档')], default='recording', max_length=20, verbose_name='状态')),
                ('jurisdiction_geo', models.TextField(blank=True, help_text='辖区范围的GeoJSON多边形坐标', verbose_name='辖区范围GeoJSON')),
                ('jurisdiction_color', models.CharField(default='#1890FF', max_length=20, verbose_name='辖区配色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('normal', '普通预警'), ('high_risk', '高风险预警')], default='normal', max_length=20, verbose_name='预警类型')),
                ('risk_level', models.CharField(choices=[('normal', '正常'), ('warning', '普通预警'), ('high_risk', '高风险预警')], default='normal', max_length=20, verbose_name='风险等级')),
                ('core_temperature', models.FloatField(verbose_name='核心温度(℃)')),
                ('heart_rate', models.IntegerField(default=0, verbose_name='心率(bpm)')),
                ('blood_oxygen', models.FloatField(default=0, verbose_name='血氧(%)')),
                ('advice_text', models.TextField(blank=True, verbose_name='健康处置预案')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='预警时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '位置轨迹',
                'verbose_name_plural': '位置轨迹',
                'db_table': 'device_location',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=75, verbose_name='心率(bpm)')),
                ('blood_oxygen', models.FloatField(default=98.0, verbose_name='血氧(%)')),
                ('blood_pressure_sys', models.IntegerField(default=120, verbose_name='收缩压(mmHg)')),
                ('blood_pressure_dia', models.IntegerField(default=80, verbose_name='舒张压(mmHg)')),
                ('step_frequency', models.IntegerField(default=0, verbose_name='步频(步/分)')),
                ('core_temperature', models.FloatField(default=37.0, verbose_name='核心温度(℃)')),
                ('latitude', models.FloatField(default=30.5722, verbose_name='纬度')),
                ('longitude', models.FloatField(default=104.0665, verbose_name='经度')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上报时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='core.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '健康数据',
                'verbose_name_plural': '健康数据',
                'db_table': 'health_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.project', verbose_name='所属项目'),
        ),
    ]
