# Generated by Django 5.2.16 on 2026-07-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='行政区划代码', max_length=12, unique=True, verbose_name='区划码')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='名称')),
                ('level', models.CharField(choices=[('province', '省级'), ('prefecture', '地级'), ('county', '县级')], db_index=True, max_length=20, verbose_name='层级')),
                ('parent_code', models.CharField(blank=True, db_index=True, help_text='上级区域的区划码', max_length=12, verbose_name='上级区划码')),
                ('geometry_geojson', models.TextField(blank=True, help_text='简化的GeoJSON几何数据', verbose_name='简化几何GeoJSON')),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='中心纬度')),
                ('center_lng', models.FloatField(blank=True, null=True, verbose_name='中心经度')),
                ('eng_name', models.CharField(blank=True, max_length=200, verbose_name='英文名')),
                ('var_name', models.CharField(blank=True, max_length=200, verbose_name='变体名')),
                ('year', models.CharField(blank=True, default='2024', max_length=10, verbose_name='年份')),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域',
                'db_table': 'region',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['level', 'parent_code'], name='region_level_836b8f_idx'), models.Index(fields=['level', 'name'], name='region_level_be0155_idx')],
            },
        ),
    ]
