# Generated by Django 5.2.16 on 2026-07-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jurisdiction_regions',
            field=models.ManyToManyField(blank=True, help_text='选择该项目管辖的行政区域', to='core.region', verbose_name='辖区区域'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.region', verbose_name='上级区域'),
        ),
    ]
