# Generated by Django 5.2.16 on 2026-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_region_eng_name_alter_region_var_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bind_status',
            field=models.CharField(choices=[('pending', '待绑定'), ('active', '已激活'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='绑定状态'),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_serial',
            field=models.CharField(blank=True, help_text='手表硬件唯一标识，注册时由手表上报', max_length=200, null=True, unique=True, verbose_name='硬件序列号'),
        ),
    ]
