# Generated by Django 5.2.16 on 2026-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_battery_worn_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='手表WiFi/蓝牙MAC地址，格式: AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='MAC地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='项目的简要描述', verbose_name='项目简介'),
        ),
    ]
