# Generated by Django 5.2.16 on 2026-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_jurisdiction_regions_region_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_index=True, help_text='行政区划代码', max_length=12, verbose_name='区划码'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('code', 'level')},
        ),
    ]
