# Generated by Django 5.2.16 on 2026-07-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_region_code_alter_region_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='eng_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='region',
            name='var_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='变体名'),
        ),
    ]
