# Generated by Django 5.2.16 on 2026-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_bind_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='手表电量百分比', null=True, verbose_name='电量(%)'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='手表固件版本号', max_length=50, verbose_name='固件版本'),
        ),
        migrations.AddField(
            model_name='device',
            name='worn',
            field=models.BooleanField(default=True, help_text='手表是否佩戴在身上', verbose_name='佩戴状态'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='core_temp_source',
            field=models.CharField(blank=True, help_text='heart_rate_estimate / kalman_estimation / informer_model_1', max_length=50, verbose_name='温度来源'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='data_quality',
            field=models.CharField(blank=True, help_text='complete / partial / invalid', max_length=30, verbose_name='数据质量'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS精度(m)'),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='steps',
            field=models.IntegerField(default=0, verbose_name='步数'),
        ),
    ]
