# Generated by Django 5.2.16 on 2026-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_description_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报坐标', null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报坐标', null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_oxygen',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='血氧(%)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_dia',
            field=models.IntegerField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='舒张压(mmHg)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure_sys',
            field=models.IntegerField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='收缩压(mmHg)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='core_temperature',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='核心温度(℃)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='心率(bpm)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='latitude',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='longitude',
            field=models.FloatField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='step_frequency',
            field=models.IntegerField(blank=True, help_text='NULL=中继未上报', null=True, verbose_name='步频(步/分)'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='steps',
            field=models.IntegerField(blank=True, null=True, verbose_name='步数'),
        ),
    ]
